version: 2.1

jobs:
  build-and-test:
    working_directory: ~/community-pulse
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout:
          path: ~/community-pulse
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install Dependencies
          command: |
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: Run Static Analysis
          command: |
            poetry run flake8 community_pulse
      - run:
          name: Run Tests
          command: |
            poetry run pytest community_pulse

workflows:
  main:
    jobs:
      - build-and-test
